# Generated by Django 4.1.3 on 2022-12-18 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                ("budget", models.PositiveIntegerField()),
                ("employment", models.PositiveIntegerField()),
                ("joined", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
